// actions
export const CONNECT = 'CONNECT'
export const JOIN = 'JOIN'
export const ON_JOIN = 'ON_JOIN'
export const HOST = 'HOST'
export const DISCONNECT = 'DISCONNECT'
export const GET_STATE = 'GET_STATE'
export const SET_STATE = 'SET_STATE'
export const SET_ENERGY = 'SET_ENERGY'
export const SET_ELEMENT = 'SET_ELEMENT'
export const SET_BUILDING = 'SET_BUILDING'
export const SET_UPGRADE = 'SET_UPGRADE'
export const SET_SELL = 'SET_SELL'
export const SET_BUILDING_DAMAGE = 'SET_BUILDING_DAMAGE'
export const SET_REPAIR = 'SET_REPAIR'
