// actions
export const CONNECT = 'CONNECT'
export const GET_STATE = 'GET_STATE'
export const SET_STATE = 'SET_STATE'
export const SET_ENERGY = 'SET_ENERGY'
export const SET_ELEMENT = 'SET_ELEMENT'
export const SET_BUILDING = 'SET_BUILDING'
export const SET_LINK = 'SET_LINK'
export const SET_UPGRADE = 'SET_UPGRADE'
export const SET_SELL = 'SET_SELL'
export const SET_DRAG_START = 'SET_DRAG_START'
export const SET_DRAG = 'SET_DRAG'
export const SET_DRAG_END = 'SET_DRAG_END'